digito = input('Digite algo: ')
print(f'o tipo primitivo desse valor é {type(digito)}')
print(f'apenas possui espaços: {digito.isspace()}')
print(f'é um número: {digito.isnumeric()}')
print(f'é alfabetico: {digito.isalpha()}')
print(f'é alfanumerico?: {digito.isalnum()}')
print(f'está em maiusculas: {digito.isupper()}')
print(f'está em maiusculas: {digito.islower()}')
print(f'está capitalizada: {digito.istitle()}')